const arregloMarcas = ["Andes Origen", "Brahma", "Budweiser", "Corona", "Patagonia", "Quilmes", "Stella Artois", "Temple"]

const categories = [1, 2, 3];

const arregloProductos = [        
    {productId:1, name:"Andes Origen Rubia lata 473cc", urlImg:"andesLataRubia.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza estilo American Pilsner, rubia con cuerpo y carácter maltoso. Aroma leve a lúpulo, cereal y toque de levadura. Es una cerveza de deleite, pero refrescante a la vez.", 
    unitPrice:148, stock:10},
    {productId:2, name:"Andes Origen Negra lata 473cc", urlImg:"andesLataNegra.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza estilo Schwarzbier alemán con aroma y sabor a tostado, cuenta con un cuerpo intenso y robusto en boca con un amargo medio. Como cerveza de deleite, armoniza su leve acidez y amargor con un suave dulzor.", 
    unitPrice:170, stock:15}, 
    {productId:3, name:"Andes Origen Roja lata 473cc", urlImg:"andesLataRoja.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza de color ámbar cobrizo, que posee un final seco y una leve acidez que la hacen muy versátil. Es una cerveza estilo Vienna Lager, su aroma a suave caramelo y leve lúpulo logran un balance perfecto.", 
    unitPrice:170, stock:20},
    {productId:4, name:"Andes Origen Criolla lata 473cc", urlImg:"andesLataCriolla.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza que hace honor a la vendimia mendocina. De color cobrizo intenso, con notas de caramelo y tostadas, suaves frutales. Cocinada con mosto de uva criolla y mosto de maltas tostadas que la hace única con un gustito bien mendocino.", 
    unitPrice:148, stock:30},
    {productId:5, name:"Andes Origen IPA lata 473cc", urlImg:"andesLataIpa.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza que se caracteriza por el amargor que le otorga su alto contenido de lúpulo. Además, contiene uva mendocina, que es un ingrediente clave para que el paladar perciba una especie de dulzor, que a su vez hace el amargor más amigable.", 
    unitPrice:170, stock:15}, 
    {productId:6, name:"Andes Origen Miel lata 473cc", urlImg:"andesLataMiel.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza del estilo Honey Beer. Tiene miel natural en su composición y aroma natural a miel. Ambos ingredientes hacen que sea una cerveza con un dulzor agradable y con un aroma y sabor característico a miel.", 
    unitPrice:170, stock:0},
    {productId:7, name:"Andes Origen Rubia botella 1L", urlImg:"andesBotellaRubia.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza estilo American Pilsner, rubia con cuerpo y carácter maltoso. Aroma leve a lúpulo, cereal y toque de levadura. Es una cerveza de deleite, pero refrescante a la vez.", 
    unitPrice:148, stock:10},
    {productId:8, name:"Andes Origen Negra botella 1L", urlImg:"andesBotellaNegra.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza estilo Schwarzbier alemán con aroma y sabor a tostado, cuenta con un cuerpo intenso y robusto en boca con un amargo medio. Como cerveza de deleite, armoniza su leve acidez y amargor con un suave dulzor.", 
    unitPrice:170, stock:15}, 
    {productId:9, name:"Andes Origen Roja botella 1L", urlImg:"andesBotellaRoja.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza de color ámbar cobrizo, que posee un final seco y una leve acidez que la hacen muy versátil. Es una cerveza estilo Vienna Lager, su aroma a suave caramelo y leve lúpulo logran un balance perfecto.", 
    unitPrice:170, stock:20},
    {productId:10, name:"Andes Origen IPA botella 1L", urlImg:"andesBotellaIpa.jpg", category:categories[1], brand:arregloMarcas[0], 
    description:"Cerveza que se caracteriza por el amargor que le otorga su alto contenido de lúpulo. Además, contiene uva mendocina, que es un ingrediente clave para que el paladar perciba una especie de dulzor, que a su vez hace el amargor más amigable.", 
    unitPrice:148, stock:30},
    
    {productId:11, name:"Brahma lata 473cc", urlImg:"brahmaLata.jpg", category:categories[0], brand:arregloMarcas[1], 
    description:"Cerveza fresca y delicada. Contiene los ingredientes más habituales de una cerveza, lo que la hace de un sabor conocido y agradable. Con una burbuja fina y de baja graduación. De color nítido, tono amarillo pálido, aromas malteados y afrutados. Con un ligero amargor.", 
    unitPrice:148, stock:50},
    {productId:12, name:"Brahma botella 340cc", urlImg:"brahmaBotellaChica.jpg", category:categories[0], brand:arregloMarcas[1], 
    description:"Cerveza fresca y delicada. Contiene los ingredientes más habituales de una cerveza, lo que la hace de un sabor conocido y agradable. Con una burbuja fina y de baja graduación. De color nítido, tono amarillo pálido, aromas malteados y afrutados. Con un ligero amargor.", 
    unitPrice:148, stock:50},
    {productId:13, name:"Brahma botella 1L", urlImg:"brahmaBotellaGrande.jpg", category:categories[0], brand:arregloMarcas[1], 
    description:"Cerveza fresca y delicada. Contiene los ingredientes más habituales de una cerveza, lo que la hace de un sabor conocido y agradable. Con una burbuja fina y de baja graduación. De color nítido, tono amarillo pálido, aromas malteados y afrutados. Con un ligero amargor.", 
    unitPrice:148, stock:50},
    
    {productId:14, name:"Budweiser lata 410cc", urlImg:"budweiserLata.jpg", category:categories[0], brand:arregloMarcas[2], 
    description:"Cerveza de color dorado pálido, y con una espuma blanca cremosa y consistente. Se perciben ligeras notas afrutadas, con aromas menos intensos a grano tostado y caramelo, y un suave toque de fondo herbal. En boca resulta ligera, bien balanceada, con amargor bajo y de final fresco.", 
    unitPrice:170, stock:60}, 
    {productId:15, name:"Budweiser botella 340cc", urlImg:"budweiserBotellaChica.jpg", category:categories[0], brand:arregloMarcas[2], 
    description:"Cerveza de color dorado pálido, y con una espuma blanca cremosa y consistente. Se perciben ligeras notas afrutadas, con aromas menos intensos a grano tostado y caramelo, y un suave toque de fondo herbal. En boca resulta ligera, bien balanceada, con amargor bajo y de final fresco.", 
    unitPrice:148, stock:50},
    {productId:16, name:"Budweiser botella 1L", urlImg:"budweiserBotellaGrande.jpg", category:categories[0], brand:arregloMarcas[2], 
    description:"Cerveza de color dorado pálido, y con una espuma blanca cremosa y consistente. Se perciben ligeras notas afrutadas, con aromas menos intensos a grano tostado y caramelo, y un suave toque de fondo herbal. En boca resulta ligera, bien balanceada, con amargor bajo y de final fresco.", 
    unitPrice:148, stock:50},
    
    {productId:17, name:"Corona lata 269cc", urlImg:"coronaLata.jpg", category:categories[1], brand:arregloMarcas[3], 
    description:"Cerveza clara y brillante, de espuma blanca y consistente. Destacan sus ligeras notas afrutadas. En boca es moderadamente dulce y recuerda al sabor del cereal. Su amargor es limpio y ligero. Es una cerveza de cuerpo medio, fresca y equilibrada.", 
    unitPrice:170, stock:100},
    {productId:18, name:"Corona botella 330cc", urlImg:"coronaBotellaChica.jpg", category:categories[1], brand:arregloMarcas[3], 
    description:"Cerveza clara y brillante, de espuma blanca y consistente. Destacan sus ligeras notas afrutadas. En boca es moderadamente dulce y recuerda al sabor del cereal. Su amargor es limpio y ligero. Es una cerveza de cuerpo medio, fresca y equilibrada.", 
    unitPrice:148, stock:50},
    {productId:19, name:"Corona botella 710cc", urlImg:"coronaBotellaGrande.jpg", category:categories[1], brand:arregloMarcas[3], 
    description:"Cerveza clara y brillante, de espuma blanca y consistente. Destacan sus ligeras notas afrutadas. En boca es moderadamente dulce y recuerda al sabor del cereal. Su amargor es limpio y ligero. Es una cerveza de cuerpo medio, fresca y equilibrada.", 
    unitPrice:148, stock:50},
    
    {productId:20, name:"Patagonia kilómetro 24.7 lata 410cc", urlImg:"patagoniaLata247.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza Session IPA, de amargor marcado otorgado por una combinación de lúpulos patagónicos. Con intenso aroma cítrico y frutal. El agregado de sauco y miel patagónicos balancean el amargor del lúpulo, aportando cierta acidez y ﬁnal seco.", 
    unitPrice:148, stock:17},
    {productId:21, name:"Patagonia Amber Lager lata 410cc", urlImg:"patagoniaLataAmberLager.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza de un suave sabor a caramelo, elaborada con una combinación del más puro lúpulo patagónico y una variedad de cuatro maltas especiales, que le dan un carácter maltoso y un color ámbar característico.", 
    unitPrice:170, stock:20}, 
    {productId:22, name:"Patagonia Bohemian Pilsener lata 410cc", urlImg:"patagoniaLataBohemianPilsener.jpg", category:categories[2], brand:arregloMarcas[4],
    description:"Cerveza dorada, muy versátil y fácil de tomar. Elaborada con una combinación de maltas Pilsen y Carapils, que le dan sabor maltoso, con buen cuerpo y un ﬁnal amargo persistente.", 
    unitPrice:170, stock:0},
    {productId:23, name:"Patagonia Kuné lata 410cc", urlImg:"patagoniaLataKune.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza Pale Ale, con perﬁl lupulado. Con una combinación de maltas especiales, que da lugar a una cerveza de color dorado bronce brillante de leve amargor y cuerpo medio. Cerveza muy balanceada y fácil de tomar.", 
    unitPrice:170, stock:0},
    {productId:24, name:"Patagonia Weisse lata 410cc", urlImg:"patagoniaLataWeisse.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza elaborada con trigo, que le da una cremosidad característica. Tiene aroma a cáscara de naranja y coriandro. De una complejidad en aromas, que resulta fácil de tomar por su refrescancia, bajo amargor y cuerpo liviano.", 
    unitPrice:170, stock:55},    
    {productId:25, name:"Patagonia kilómetro 24.7 botella 730cc", urlImg:"patagoniaBotella247.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza Session IPA, de amargor marcado otorgado por una combinación de lúpulos patagónicos. Con intenso aroma cítrico y frutal. El agregado de sauco y miel patagónicos balancean el amargor del lúpulo, aportando cierta acidez y ﬁnal seco.", 
    unitPrice:148, stock:17},
    {productId:26, name:"Patagonia Amber Lager botella 730cc", urlImg:"patagoniaBotellaAmberLager.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza de un suave sabor a caramelo, elaborada con una combinación del más puro lúpulo patagónico y una variedad de cuatro maltas especiales, que le dan un carácter maltoso y un color ámbar característico.", 
    unitPrice:170, stock:20}, 
    {productId:27, name:"Patagonia Bohemian Pilsener botella 730cc", urlImg:"patagoniaBotellaBohemianPilsener.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza dorada, muy versátil y fácil de tomar. Elaborada con una combinación de maltas Pilsen y Carapils, que le dan sabor maltoso, con buen cuerpo y un ﬁnal amargo persistente.", 
    unitPrice:170, stock:0},
    {productId:28, name:"Patagonia Kuné botella 730cc", urlImg:"patagoniaBotellaKune.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza Pale Ale, con perﬁl lupulado. Con una combinación de maltas especiales, que da lugar a una cerveza de color dorado bronce brillante de leve amargor y cuerpo medio. Cerveza muy balanceada y fácil de tomar.", 
    unitPrice:170, stock:0},
    {productId:29, name:"Patagonia Weisse botella 730cc", urlImg:"patagoniaBotellaWeisse.jpg", category:categories[2], brand:arregloMarcas[4], 
    description:"Cerveza elaborada con trigo, que le da una cremosidad característica. Tiene aroma a cáscara de naranja y coriandro. De una complejidad en aromas, que resulta fácil de tomar por su refrescancia, bajo amargor y cuerpo liviano.", 
    unitPrice:170, stock:55},   
    
    {productId:30, name:"Quilmes Bock lata 473cc", urlImg:"quilmesLataBock.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza negra y amarga. Cerveza de cuerpo robusto y sabor acaramelado. Su intenso amargor es por su alta cantidad de lúpulo y su color oscuro borravino provienen de las tres variedades de malta con las que se elabora.", 
    unitPrice:170, stock:60},
    {productId:31, name:"Quilmes Clásica lata 473cc", urlImg:"quilmesLataClasica.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza lager perfectamente equilibrada, transparente dorada, buen nivel de espuma y sabor. Para hacerla se utilizan sólo ingredientes naturales que crecen en los campos de Argentina.", 
    unitPrice:170, stock:15},
    {productId:32, name:"Quilmes Doble Malta lata 410cc", urlImg:"quilmesLataDobleMalta.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Las maltas Pilsen y Carapils juntas hacen que esta cerveza tenga doble sabor, un cuerpo más intenso y una espuma más persistente. Tiene notas a cereal, leve dulzor y un amargor que contrarresta y balancea su perfil.", 
    unitPrice:170, stock:10},
    {productId:33, name:"Quilmes Red Lager lata 473cc", urlImg:"quilmesLataRedLager.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza roja. Cerveza de cuerpo medio, color cobrizo y acaramelada. Esta variedad debe sus características al particular proceso de caramelización de las maltas con las que se elabora.", 
    unitPrice:170, stock:5},
    {productId:34, name:"Quilmes Stout lata 473cc", urlImg:"quilmesLataStout.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza negra y dulce. De color marrón oscuro, de cuerpo y espuma cremosa. Tiene un intenso aroma torrado y un leve amargor en paladar que se compensa con el sabor dulce de sus notas de chocolate y café.", 
    unitPrice:170, stock:200},
    {productId:35, name:"Quilmes Bock botella 1L", urlImg:"quilmesBotellaBock.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza negra y amarga. Cerveza de cuerpo robusto y sabor acaramelado. Su intenso amargor es por su alta cantidad de lúpulo y su color oscuro borravino provienen de las tres variedades de malta con las que se elabora.", 
    unitPrice:170, stock:60},
    {productId:36, name:"Quilmes Clásica botella 1L", urlImg:"quilmesBotellaClasica.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza lager perfectamente equilibrada, transparente dorada, buen nivel de espuma y sabor. Para hacerla se utilizan sólo ingredientes naturales que crecen en los campos de Argentina.", 
    unitPrice:170, stock:15},
    {productId:37, name:"Quilmes Doble Malta botella 1L", urlImg:"quilmesBotellaDobleMalta.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Las maltas Pilsen y Carapils juntas hacen que esta cerveza tenga doble sabor, un cuerpo más intenso y una espuma más persistente. Tiene notas a cereal, leve dulzor y un amargor que contrarresta y balancea su perfil.", 
    unitPrice:170, stock:10},
    {productId:38, name:"Quilmes Red Lager botella 1L", urlImg:"quilmesBotellaRedLager.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza roja. Cerveza de cuerpo medio, color cobrizo y acaramelada. Esta variedad debe sus características al particular proceso de caramelización de las maltas con las que se elabora.", 
    unitPrice:170, stock:5},
    {productId:39, name:"Quilmes Stout botella 1L", urlImg:"quilmesBotellaStout.jpg", category:categories[0], brand:arregloMarcas[5], 
    description:"Cerveza negra y dulce. De color marrón oscuro, de cuerpo y espuma cremosa. Tiene un intenso aroma torrado y un leve amargor en paladar que se compensa con el sabor dulce de sus notas de chocolate y café.", 
    unitPrice:170, stock:200},
    
    {productId:40, name:"Stella Artois Rubia lata 269cc", urlImg:"stellaLataChicaRubia.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza de color dorado pálido, muy brillante y con una espuma consistente. Una cerveza muy equilibrada donde predominan moderadas notas a frutas blancas y de cereal que resaltan levemente sobre un aroma herbal. En boca presenta una sensación suave, ligera de amargo y con efecto refrescante.", 
    unitPrice:170, stock:0},
    {productId:41, name:"Stella Artois Rubia lata 473cc", urlImg:"stellaLataGrandeRubia.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza de color dorado pálido, muy brillante y con una espuma consistente. Una cerveza muy equilibrada donde predominan moderadas notas a frutas blancas y de cereal que resaltan levemente sobre un aroma herbal. En boca presenta una sensación suave, ligera de amargo y con efecto refrescante.", 
    unitPrice:170, stock:30},
    {productId:42, name:"Stella Artois Negra lata 269cc", urlImg:"stellaLataChicaNegra.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza negra premium. De espuma cremosa, color negro intenso, cuerpo equilibrado, y aroma a maltas tostadas. Es el maridaje ideal para lo dulce y agridulce.", 
    unitPrice:170, stock:35},
    {productId:43, name:"Stella Artois Negra lata 473cc", urlImg:"stellaLataGrandeNegra.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza negra premium. De espuma cremosa, color negro intenso, cuerpo equilibrado, y aroma a maltas tostadas. Es el maridaje ideal para lo dulce y agridulce.", 
    unitPrice:170, stock:40},
    {productId:44, name:"Stella Artois Rubia botella 330cc", urlImg:"stellaBotellaChicaRubia.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza de color dorado pálido, muy brillante y con una espuma consistente. Una cerveza muy equilibrada donde predominan moderadas notas a frutas blancas y de cereal que resaltan levemente sobre un aroma herbal. En boca presenta una sensación suave, ligera de amargo y con efecto refrescante.", 
    unitPrice:170, stock:0},
    {productId:45, name:"Stella Artois Rubia botella 975cc", urlImg:"stellaBotellaGrandeRubia.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza de color dorado pálido, muy brillante y con una espuma consistente. Una cerveza muy equilibrada donde predominan moderadas notas a frutas blancas y de cereal que resaltan levemente sobre un aroma herbal. En boca presenta una sensación suave, ligera de amargo y con efecto refrescante.", 
    unitPrice:170, stock:30},
    {productId:46, name:"Stella Artois Negra botella 330cc", urlImg:"stellaBotellaChicaNegra.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza negra premium. De espuma cremosa, color negro intenso, cuerpo equilibrado, y aroma a maltas tostadas. Es el maridaje ideal para lo dulce y agridulce.", 
    unitPrice:170, stock:35},
    {productId:47, name:"Stella Artois Negra botella 975cc", urlImg:"stellaBotellaGrandeNegra.jpg", category:categories[1], brand:arregloMarcas[6], 
    description:"Cerveza negra premium. De espuma cremosa, color negro intenso, cuerpo equilibrado, y aroma a maltas tostadas. Es el maridaje ideal para lo dulce y agridulce.", 
    unitPrice:170, stock:40},
    
    {productId:48, name:"Temple Cósmica lata 473cc", urlImg:"templeLataCosmica.jpg", category:categories[2], brand:arregloMarcas[7], 
    description:"Es una cerveza lager lupulada, aromática, fresca y de bajo amargor, lo que la convierte en la favorita de cualquier paladar cervecero.", 
    unitPrice:170, stock:10},
    {productId:49, name:"Temple Honey lata 473cc", urlImg:"templeLataHoney.jpg", category:categories[2], brand:arregloMarcas[7], 
    description:"Cerveza con sabor a miel. Pensando en la sustentabilidad, se usa miel orgánica que se agrega en la etapa de maduración, evitando que se transforme en alcohol, resalte el aroma y el sabor.", 
    unitPrice:170, stock:30},
    {productId:50, name:"Temple Wolf IPA lata 473cc", urlImg:"templeLataIpa.jpg", category:categories[2], brand:arregloMarcas[7], 
    description:"Con un perfil muy americano, es una cerveza IPA cítrica y frutal, que tiene un magnífico balance entre aroma, sabor, amargor y tomabilidad.", 
    unitPrice:170, stock:0},
    {productId:51, name:"Temple Scottish lata 473cc", urlImg:"templeLataScottish.jpg", category:categories[2], brand:arregloMarcas[7], 
    description:"Cerveza de color cobrizo que refleja su elegancia y complejidad en sus aromas. Combina maltas especiales que le dan un perfil a tostado y caramelo.", 
    unitPrice:170, stock:25},
];

export const getProducts = () => {
    return arregloProductos
}

export const getProductById = (id) => {
    return arregloProductos.find(object => object.productId === Number(id));
}

export const getProductsByCategory = (id) => {
    return arregloProductos.filter(object => object.category === Number(id));
}